apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  strategy: {}
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mqtt-config
          mountPath: /mosquitto/
          subPath: mosquitto.conf
        - name: "mqtt-data"
          mountPath: "/mosquitto/"
      volumes:
      - name: data
        pesristentVolumeclaim:
          claimName: mqtt-data


      - name: mqtt-config
        configMap:
          name: mosquitto-configmap
        persistentVolumeClaim:
          claimName: "mongo-data"
