apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-co2-deployment
  labels:
    app: sim-co2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sim-co2
  template:
    metadata:
      labels:
        app: sim-co2
    spec:
      containers:
        - args:
            - npm
            - start
            - "10"
            - "2345"
            - "500"
            - X
            - "1997"
            - "2502"
          image: tomisboy/pub:sim
          imagePullPolicy: Always
          name: sim-co2
