apiVersion: apps/v1
kind: Deployment
metadata:
  name: rectemp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: rectemp
  template:
    metadata:
      labels:
        app: rectemp
    spec:
      containers:
      - name: rectemp
        image: tomisboy/pub:rectemp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password





