version: "3.5"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_custom_vol

networks:
  default:
    name: mqtt
    external: true


