apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt

spec:
  replicas: 1
  selector:
matchLabels:
  name: mqtt
  template:
    metadata:
      labels:
        name: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto
          ports:
          - containerPort: 1883
      volumeMounts:
          - name: mqtt-config
            mountPath: /mosquitto/
            subPath: mosquitto.conf
          - name: "mqtt-data"
            mountPath: "/mosquitto/"
      volumes:
      - name: mqtt-config
        configMap:
          name: mosquitto-configmap
      - name: data
      pesristentVolumeclaim:
          claimName: mqtt-data

