version: "3"
services:  
  rec-temperatur:
    build: .
    image: tomisboy/pub:temperatur
    container_name: temperatur
    ports:
      - "5000:5000"

networks:
  default:
    name: mqtt
    external: true