version: "3.5"

services:  
  rectemp:
    build: ./rectemp
    image: tomisboy/pub:rectemp
    container_name: rectemp
    ports:
      - "5000:5000"


  temp-alert:
    build: ./temp-alert
    image: tomisboy/pub:temp-alert
    container_name: temp-alert


  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./mqtt/mosquitto/config:/mosquitto/config
      - ./mqtt/mosquitto/data:/mosquitto/data
      - ./mqtt/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wird-nicht-verwendet-Anonymer-Zugriff-auf-DB-gesetzt
      - MONGO_INITDB_ROOT_PASSWORD=wird-nicht-verwendet-Anonymer-Zugriff-auf-DB-gesetzt
    command: [--auth]
    volumes: 
      - mongodb_volume:/data/db
volumes:
  mongodb_volume:



networks:
  default:
    name: mqtt
    external: true