version: "3.5"
services:  
  sim-temperatur:
    build: .
    image: tomisboy/pub:sim
    container_name: sim-temperatur
    command: ["npm", "start", "5" , "1234",  "500" , "T" , "10" , "100"]
    network_mode: "host"


  sim-co2:
    build: .
    image: tomisboy/pub:sim
    container_name: sim-co2
    command: ["npm", "start", "5" , "2345",  "500" , "X" , "1997" , "2502"]
    network_mode: "host"

  sim-people:
    build: .
    image: tomisboy/pub:sim
    container_name: sim-people
    command: ["npm", "start", "5" , "3456",  "500" , "P" , "0" , "50"]
    network_mode: "host"

  sim-luftfeuchtigkeit:
    build: .
    image: tomisboy/pub:sim
    container_name: sim-luftfeuchtigkeit
    command: ["npm", "start", "5" , "4567",  "500" , "H" , "20" , "70"]
    network_mode: "host"

  sim-feinstaub:
    build: .
    image: tomisboy/pub:sim
    container_name: sim-feinstaub
    command: ["npm", "start", "5" , "5678",  "500" , "p" , "2" , "6"]
    network_mode: "host"


    
#networks:
#  default:
#    name: mqtt
#    external: true