apiVersion: apps/v1
kind: Deployment
metadata:
  name: rectemp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rectemp
  template:
    metadata:
      labels:
        app: rectemp
    spec:
      containers:
      - name: rectemp
        image: tomisboy/pub:rectemp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000







